[global]
# Skip the email prompt
email = "subflw47@gmail.com"

[server]
# Allow external connections
address = "0.0.0.0"
port = 8501

[browser]
# Don't automatically open browser
gatherUsageStats = false 